// Code generated by go-vk from vk.xml at 2025-02-06 09:21:30.4299266 -0500 EST m=+2.281565501. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
