//go:build darwin

// Code generated by go-vk from vk.xml at 2025-11-20 11:05:56.8632382 -0500 EST m=+2.104650201. DO NOT EDIT.

package vk

// CAMetalLayer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/CAMetalLayer.html
type CAMetalLayer struct{}
