// Code generated by go-vk from vk-1.3.270.xml at 2023-11-22 10:57:10.53584 -0500 EST m=+3.061284658. DO NOT EDIT.

package vk

import "unsafe"

// DeviceAddress: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceAddress.html
type DeviceAddress uint64

// DeviceSize: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceSize.html
type DeviceSize uint64

// Flags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFlags.html
type Flags uint32

// Flags64: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFlags64.html
type Flags64 uint64

// PFN_vkAllocationFunction: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkAllocationFunction.html
type PFN_vkAllocationFunction unsafe.Pointer

// PFN_vkDebugReportCallbackEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkDebugReportCallbackEXT.html
type PFN_vkDebugReportCallbackEXT unsafe.Pointer

// PFN_vkDebugUtilsMessengerCallbackEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkDebugUtilsMessengerCallbackEXT.html
type PFN_vkDebugUtilsMessengerCallbackEXT unsafe.Pointer

// PFN_vkDeviceMemoryReportCallbackEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkDeviceMemoryReportCallbackEXT.html
type PFN_vkDeviceMemoryReportCallbackEXT unsafe.Pointer

// PFN_vkFreeFunction: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkFreeFunction.html
type PFN_vkFreeFunction unsafe.Pointer

// PFN_vkGetInstanceProcAddrLUNARG: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkGetInstanceProcAddrLUNARG.html
type PFN_vkGetInstanceProcAddrLUNARG unsafe.Pointer

// PFN_vkInternalAllocationNotification: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkInternalAllocationNotification.html
type PFN_vkInternalAllocationNotification unsafe.Pointer

// PFN_vkInternalFreeNotification: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkInternalFreeNotification.html
type PFN_vkInternalFreeNotification unsafe.Pointer

// PFN_vkReallocationFunction: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkReallocationFunction.html
type PFN_vkReallocationFunction unsafe.Pointer

// PFN_vkVoidFunction: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/PFN_vkVoidFunction.html
type PFN_vkVoidFunction unsafe.Pointer

// RemoteAddressNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkRemoteAddressNV.html
type RemoteAddressNV unsafe.Pointer

// SampleMask: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSampleMask.html
type SampleMask uint32

// Bool32: Note that go-vk uses standard Go bools throughout the public API. Bool32 is only used internally and is automatically translated for you.
// See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBool32.html
type Bool32 uint32
