// Code generated by go-vk from vk.xml at 2023-12-27 07:44:41.1951994 -0500 EST m=+2.378804901. DO NOT EDIT.

package vk

// ExportMetalObjectTypeFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExportMetalObjectTypeFlagsEXT.html
type ExportMetalObjectTypeFlagsEXT Flags

// MetalSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMetalSurfaceCreateFlagsEXT.html
type MetalSurfaceCreateFlagsEXT Flags
