// Code generated by go-vk from vk.xml at 2025-11-13 11:56:02.739896 -0500 EST m=+0.869474959. DO NOT EDIT.

package vk

// AccelerationStructureCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureCreateFlagsKHR.html
type AccelerationStructureCreateFlagsKHR Flags

// AccelerationStructureMotionInfoFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureMotionInfoFlagsNV.html
type AccelerationStructureMotionInfoFlagsNV Flags

// AccelerationStructureMotionInstanceFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureMotionInstanceFlagsNV.html
type AccelerationStructureMotionInstanceFlagsNV Flags

// AccessFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAccessFlags.html
type AccessFlags Flags

// AccessFlags2KHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAccessFlags2KHR.html
type AccessFlags2KHR Flags64

// AcquireProfilingLockFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAcquireProfilingLockFlagsKHR.html
type AcquireProfilingLockFlagsKHR Flags

// AttachmentDescriptionFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAttachmentDescriptionFlags.html
type AttachmentDescriptionFlags Flags

// BufferCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBufferCreateFlags.html
type BufferCreateFlags Flags

// BufferUsageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBufferUsageFlags.html
type BufferUsageFlags Flags

// BufferViewCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBufferViewCreateFlags.html
type BufferViewCreateFlags Flags

// BuildAccelerationStructureFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBuildAccelerationStructureFlagsKHR.html
type BuildAccelerationStructureFlagsKHR Flags

// BuildAccelerationStructureFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBuildAccelerationStructureFlagsNV.html
type BuildAccelerationStructureFlagsNV = BuildAccelerationStructureFlagsKHR

// ColorComponentFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkColorComponentFlags.html
type ColorComponentFlags Flags

// CommandBufferResetFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandBufferResetFlags.html
type CommandBufferResetFlags Flags

// CommandBufferUsageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandBufferUsageFlags.html
type CommandBufferUsageFlags Flags

// CommandPoolCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandPoolCreateFlags.html
type CommandPoolCreateFlags Flags

// CommandPoolResetFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandPoolResetFlags.html
type CommandPoolResetFlags Flags

// CommandPoolTrimFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandPoolTrimFlags.html
type CommandPoolTrimFlags Flags

// CommandPoolTrimFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandPoolTrimFlagsKHR.html
type CommandPoolTrimFlagsKHR = CommandPoolTrimFlags

// CompositeAlphaFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCompositeAlphaFlagsKHR.html
type CompositeAlphaFlagsKHR Flags

// ConditionalRenderingFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkConditionalRenderingFlagsEXT.html
type ConditionalRenderingFlagsEXT Flags

// CullModeFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCullModeFlags.html
type CullModeFlags Flags

// DebugReportFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugReportFlagsEXT.html
type DebugReportFlagsEXT Flags

// DebugUtilsMessageSeverityFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugUtilsMessageSeverityFlagsEXT.html
type DebugUtilsMessageSeverityFlagsEXT Flags

// DebugUtilsMessageTypeFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugUtilsMessageTypeFlagsEXT.html
type DebugUtilsMessageTypeFlagsEXT Flags

// DebugUtilsMessengerCallbackDataFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugUtilsMessengerCallbackDataFlagsEXT.html
type DebugUtilsMessengerCallbackDataFlagsEXT Flags

// DebugUtilsMessengerCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugUtilsMessengerCreateFlagsEXT.html
type DebugUtilsMessengerCreateFlagsEXT Flags

// DependencyFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDependencyFlags.html
type DependencyFlags Flags

// DescriptorBindingFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorBindingFlags.html
type DescriptorBindingFlags Flags

// DescriptorBindingFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorBindingFlagsEXT.html
type DescriptorBindingFlagsEXT = DescriptorBindingFlags

// DescriptorPoolCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorPoolCreateFlags.html
type DescriptorPoolCreateFlags Flags

// DescriptorPoolResetFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorPoolResetFlags.html
type DescriptorPoolResetFlags Flags

// DescriptorSetLayoutCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayoutCreateFlags.html
type DescriptorSetLayoutCreateFlags Flags

// DescriptorUpdateTemplateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorUpdateTemplateCreateFlags.html
type DescriptorUpdateTemplateCreateFlags Flags

// DescriptorUpdateTemplateCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorUpdateTemplateCreateFlagsKHR.html
type DescriptorUpdateTemplateCreateFlagsKHR = DescriptorUpdateTemplateCreateFlags

// DeviceCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceCreateFlags.html
type DeviceCreateFlags Flags

// DeviceDiagnosticsConfigFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceDiagnosticsConfigFlagsNV.html
type DeviceDiagnosticsConfigFlagsNV Flags

// DeviceGroupPresentModeFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceGroupPresentModeFlagsKHR.html
type DeviceGroupPresentModeFlagsKHR Flags

// DeviceMemoryReportFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceMemoryReportFlagsEXT.html
type DeviceMemoryReportFlagsEXT Flags

// DeviceQueueCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceQueueCreateFlags.html
type DeviceQueueCreateFlags Flags

// DisplayModeCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDisplayModeCreateFlagsKHR.html
type DisplayModeCreateFlagsKHR Flags

// DisplayPlaneAlphaFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDisplayPlaneAlphaFlagsKHR.html
type DisplayPlaneAlphaFlagsKHR Flags

// DisplaySurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDisplaySurfaceCreateFlagsKHR.html
type DisplaySurfaceCreateFlagsKHR Flags

// EventCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkEventCreateFlags.html
type EventCreateFlags Flags

// ExternalFenceFeatureFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalFenceFeatureFlags.html
type ExternalFenceFeatureFlags Flags

// ExternalFenceFeatureFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalFenceFeatureFlagsKHR.html
type ExternalFenceFeatureFlagsKHR = ExternalFenceFeatureFlags

// ExternalFenceHandleTypeFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalFenceHandleTypeFlags.html
type ExternalFenceHandleTypeFlags Flags

// ExternalFenceHandleTypeFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalFenceHandleTypeFlagsKHR.html
type ExternalFenceHandleTypeFlagsKHR = ExternalFenceHandleTypeFlags

// ExternalMemoryFeatureFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalMemoryFeatureFlags.html
type ExternalMemoryFeatureFlags Flags

// ExternalMemoryFeatureFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalMemoryFeatureFlagsKHR.html
type ExternalMemoryFeatureFlagsKHR = ExternalMemoryFeatureFlags

// ExternalMemoryFeatureFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalMemoryFeatureFlagsNV.html
type ExternalMemoryFeatureFlagsNV Flags

// ExternalMemoryHandleTypeFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalMemoryHandleTypeFlags.html
type ExternalMemoryHandleTypeFlags Flags

// ExternalMemoryHandleTypeFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalMemoryHandleTypeFlagsKHR.html
type ExternalMemoryHandleTypeFlagsKHR = ExternalMemoryHandleTypeFlags

// ExternalMemoryHandleTypeFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalMemoryHandleTypeFlagsNV.html
type ExternalMemoryHandleTypeFlagsNV Flags

// ExternalSemaphoreFeatureFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalSemaphoreFeatureFlags.html
type ExternalSemaphoreFeatureFlags Flags

// ExternalSemaphoreFeatureFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalSemaphoreFeatureFlagsKHR.html
type ExternalSemaphoreFeatureFlagsKHR = ExternalSemaphoreFeatureFlags

// ExternalSemaphoreHandleTypeFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalSemaphoreHandleTypeFlags.html
type ExternalSemaphoreHandleTypeFlags Flags

// ExternalSemaphoreHandleTypeFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExternalSemaphoreHandleTypeFlagsKHR.html
type ExternalSemaphoreHandleTypeFlagsKHR = ExternalSemaphoreHandleTypeFlags

// FenceCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFenceCreateFlags.html
type FenceCreateFlags Flags

// FenceImportFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFenceImportFlags.html
type FenceImportFlags Flags

// FenceImportFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFenceImportFlagsKHR.html
type FenceImportFlagsKHR = FenceImportFlags

// FormatFeatureFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFormatFeatureFlags.html
type FormatFeatureFlags Flags

// FormatFeatureFlags2KHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFormatFeatureFlags2KHR.html
type FormatFeatureFlags2KHR Flags64

// FramebufferCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFramebufferCreateFlags.html
type FramebufferCreateFlags Flags

// GeometryFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkGeometryFlagsKHR.html
type GeometryFlagsKHR Flags

// GeometryFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkGeometryFlagsNV.html
type GeometryFlagsNV = GeometryFlagsKHR

// GeometryInstanceFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkGeometryInstanceFlagsKHR.html
type GeometryInstanceFlagsKHR Flags

// GeometryInstanceFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkGeometryInstanceFlagsNV.html
type GeometryInstanceFlagsNV = GeometryInstanceFlagsKHR

// HeadlessSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkHeadlessSurfaceCreateFlagsEXT.html
type HeadlessSurfaceCreateFlagsEXT Flags

// ImageAspectFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageAspectFlags.html
type ImageAspectFlags Flags

// ImageCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageCreateFlags.html
type ImageCreateFlags Flags

// ImageUsageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageUsageFlags.html
type ImageUsageFlags Flags

// ImageViewCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageViewCreateFlags.html
type ImageViewCreateFlags Flags

// IndirectCommandsLayoutUsageFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkIndirectCommandsLayoutUsageFlagsNV.html
type IndirectCommandsLayoutUsageFlagsNV Flags

// IndirectStateFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkIndirectStateFlagsNV.html
type IndirectStateFlagsNV Flags

// InstanceCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkInstanceCreateFlags.html
type InstanceCreateFlags Flags

// MemoryAllocateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMemoryAllocateFlags.html
type MemoryAllocateFlags Flags

// MemoryAllocateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMemoryAllocateFlagsKHR.html
type MemoryAllocateFlagsKHR = MemoryAllocateFlags

// MemoryHeapFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMemoryHeapFlags.html
type MemoryHeapFlags Flags

// MemoryMapFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMemoryMapFlags.html
type MemoryMapFlags Flags

// MemoryPropertyFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMemoryPropertyFlags.html
type MemoryPropertyFlags Flags

// PeerMemoryFeatureFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPeerMemoryFeatureFlags.html
type PeerMemoryFeatureFlags Flags

// PeerMemoryFeatureFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPeerMemoryFeatureFlagsKHR.html
type PeerMemoryFeatureFlagsKHR = PeerMemoryFeatureFlags

// PerformanceCounterDescriptionFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPerformanceCounterDescriptionFlagsKHR.html
type PerformanceCounterDescriptionFlagsKHR Flags

// PipelineCacheCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCacheCreateFlags.html
type PipelineCacheCreateFlags Flags

// PipelineColorBlendStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineColorBlendStateCreateFlags.html
type PipelineColorBlendStateCreateFlags Flags

// PipelineCompilerControlFlagsAMD: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCompilerControlFlagsAMD.html
type PipelineCompilerControlFlagsAMD Flags

// PipelineCoverageModulationStateCreateFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCoverageModulationStateCreateFlagsNV.html
type PipelineCoverageModulationStateCreateFlagsNV Flags

// PipelineCoverageReductionStateCreateFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCoverageReductionStateCreateFlagsNV.html
type PipelineCoverageReductionStateCreateFlagsNV Flags

// PipelineCoverageToColorStateCreateFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCoverageToColorStateCreateFlagsNV.html
type PipelineCoverageToColorStateCreateFlagsNV Flags

// PipelineCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCreateFlags.html
type PipelineCreateFlags Flags

// PipelineCreationFeedbackFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCreationFeedbackFlagsEXT.html
type PipelineCreationFeedbackFlagsEXT Flags

// PipelineDepthStencilStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineDepthStencilStateCreateFlags.html
type PipelineDepthStencilStateCreateFlags Flags

// PipelineDiscardRectangleStateCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineDiscardRectangleStateCreateFlagsEXT.html
type PipelineDiscardRectangleStateCreateFlagsEXT Flags

// PipelineDynamicStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineDynamicStateCreateFlags.html
type PipelineDynamicStateCreateFlags Flags

// PipelineInputAssemblyStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineInputAssemblyStateCreateFlags.html
type PipelineInputAssemblyStateCreateFlags Flags

// PipelineLayoutCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineLayoutCreateFlags.html
type PipelineLayoutCreateFlags Flags

// PipelineMultisampleStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineMultisampleStateCreateFlags.html
type PipelineMultisampleStateCreateFlags Flags

// PipelineRasterizationConservativeStateCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineRasterizationConservativeStateCreateFlagsEXT.html
type PipelineRasterizationConservativeStateCreateFlagsEXT Flags

// PipelineRasterizationDepthClipStateCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineRasterizationDepthClipStateCreateFlagsEXT.html
type PipelineRasterizationDepthClipStateCreateFlagsEXT Flags

// PipelineRasterizationStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineRasterizationStateCreateFlags.html
type PipelineRasterizationStateCreateFlags Flags

// PipelineRasterizationStateStreamCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineRasterizationStateStreamCreateFlagsEXT.html
type PipelineRasterizationStateStreamCreateFlagsEXT Flags

// PipelineShaderStageCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineShaderStageCreateFlags.html
type PipelineShaderStageCreateFlags Flags

// PipelineStageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineStageFlags.html
type PipelineStageFlags Flags

// PipelineStageFlags2KHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineStageFlags2KHR.html
type PipelineStageFlags2KHR Flags64

// PipelineTessellationStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineTessellationStateCreateFlags.html
type PipelineTessellationStateCreateFlags Flags

// PipelineVertexInputStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineVertexInputStateCreateFlags.html
type PipelineVertexInputStateCreateFlags Flags

// PipelineViewportStateCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineViewportStateCreateFlags.html
type PipelineViewportStateCreateFlags Flags

// PipelineViewportSwizzleStateCreateFlagsNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineViewportSwizzleStateCreateFlagsNV.html
type PipelineViewportSwizzleStateCreateFlagsNV Flags

// PrivateDataSlotCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPrivateDataSlotCreateFlagsEXT.html
type PrivateDataSlotCreateFlagsEXT Flags

// QueryControlFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryControlFlags.html
type QueryControlFlags Flags

// QueryPipelineStatisticFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryPipelineStatisticFlags.html
type QueryPipelineStatisticFlags Flags

// QueryPoolCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryPoolCreateFlags.html
type QueryPoolCreateFlags Flags

// QueryResultFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryResultFlags.html
type QueryResultFlags Flags

// QueueFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueueFlags.html
type QueueFlags Flags

// RenderPassCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkRenderPassCreateFlags.html
type RenderPassCreateFlags Flags

// RenderingFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkRenderingFlagsKHR.html
type RenderingFlagsKHR Flags

// ResolveModeFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkResolveModeFlags.html
type ResolveModeFlags Flags

// ResolveModeFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkResolveModeFlagsKHR.html
type ResolveModeFlagsKHR = ResolveModeFlags

// SampleCountFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSampleCountFlags.html
type SampleCountFlags Flags

// SamplerCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSamplerCreateFlags.html
type SamplerCreateFlags Flags

// SemaphoreCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSemaphoreCreateFlags.html
type SemaphoreCreateFlags Flags

// SemaphoreImportFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSemaphoreImportFlags.html
type SemaphoreImportFlags Flags

// SemaphoreImportFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSemaphoreImportFlagsKHR.html
type SemaphoreImportFlagsKHR = SemaphoreImportFlags

// SemaphoreWaitFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSemaphoreWaitFlags.html
type SemaphoreWaitFlags Flags

// SemaphoreWaitFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSemaphoreWaitFlagsKHR.html
type SemaphoreWaitFlagsKHR = SemaphoreWaitFlags

// ShaderCorePropertiesFlagsAMD: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkShaderCorePropertiesFlagsAMD.html
type ShaderCorePropertiesFlagsAMD Flags

// ShaderModuleCreateFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkShaderModuleCreateFlags.html
type ShaderModuleCreateFlags Flags

// ShaderStageFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkShaderStageFlags.html
type ShaderStageFlags Flags

// SparseImageFormatFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSparseImageFormatFlags.html
type SparseImageFormatFlags Flags

// SparseMemoryBindFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSparseMemoryBindFlags.html
type SparseMemoryBindFlags Flags

// StencilFaceFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkStencilFaceFlags.html
type StencilFaceFlags Flags

// SubgroupFeatureFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSubgroupFeatureFlags.html
type SubgroupFeatureFlags Flags

// SubmitFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSubmitFlagsKHR.html
type SubmitFlagsKHR Flags

// SubpassDescriptionFlags: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSubpassDescriptionFlags.html
type SubpassDescriptionFlags Flags

// SurfaceCounterFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSurfaceCounterFlagsEXT.html
type SurfaceCounterFlagsEXT Flags

// SurfaceTransformFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSurfaceTransformFlagsKHR.html
type SurfaceTransformFlagsKHR Flags

// SwapchainCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSwapchainCreateFlagsKHR.html
type SwapchainCreateFlagsKHR Flags

// ToolPurposeFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkToolPurposeFlagsEXT.html
type ToolPurposeFlagsEXT Flags

// ValidationCacheCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkValidationCacheCreateFlagsEXT.html
type ValidationCacheCreateFlagsEXT Flags
