// Code generated by go-vk from vk-1.3.270.xml at 2023-11-22 10:57:11.047211 -0500 EST m=+3.572658855. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
