// Code generated by go-vk from vk.xml. DO NOT EDIT.

package vk

// ExportMetalObjectTypeFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExportMetalObjectTypeFlagsEXT.html
type ExportMetalObjectTypeFlagsEXT Flags

// MetalSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMetalSurfaceCreateFlagsEXT.html
type MetalSurfaceCreateFlagsEXT Flags
