//go:build darwin
// Code generated by go-vk from vk-1.3.270.xml at 2023-11-22 10:57:10.831983 -0500 EST m=+3.357429502. DO NOT EDIT.

package vk

import "unsafe"

// CreateMetalSurfaceEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateMetalSurfaceEXT.html
func CreateMetalSurfaceEXT(instance Instance, createInfo *MetalSurfaceCreateInfoEXT, allocator *AllocationCallbacks) (surface SurfaceKHR, r error) {
	// Parameter is a singular input, requires translation - createInfo
	var pCreateInfo *_vkMetalSurfaceCreateInfoEXT
	if createInfo != nil {
		pCreateInfo = createInfo.Vulkanize()
	}

	// Parameter is a singular input, pass direct - allocator
	var pAllocator unsafe.Pointer
	if allocator != nil {
		pAllocator = unsafe.Pointer(allocator)
	}

	// surface is a binding-allocated single return value and will be populated by Vulkan
	ptr_pSurface := &surface

	r = Result(execTrampoline(vkCreateMetalSurfaceEXT, uintptr(instance), uintptr(unsafe.Pointer(pCreateInfo)), uintptr(unsafe.Pointer(pAllocator)), uintptr(unsafe.Pointer(ptr_pSurface))))

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkCreateMetalSurfaceEXT = &vkCommand{"vkCreateMetalSurfaceEXT", 4, true, nil}

// ExportMetalObjectsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkExportMetalObjectsEXT.html
func ExportMetalObjectsEXT(device Device) (metalObjectsInfo ExportMetalObjectsInfoEXT) {
	// metalObjectsInfo is a binding-allocated single return value and will be populated by Vulkan, but requiring translation
	var pMetalObjectsInfo *_vkExportMetalObjectsInfoEXT = metalObjectsInfo.Vulkanize()

	execTrampoline(vkExportMetalObjectsEXT, uintptr(device), uintptr(unsafe.Pointer(pMetalObjectsInfo)))

	metalObjectsInfo = *(pMetalObjectsInfo.Goify())
	return
}

var vkExportMetalObjectsEXT = &vkCommand{"vkExportMetalObjectsEXT", 2, true, nil}
