// Code generated by go-vk from vk-1.3.270.xml at 2023-11-22 10:57:10.126508 -0500 EST m=+2.651950186. DO NOT EDIT.

package vk

// API_VERSION: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_API_VERSION.html
var API_VERSION = MAKE_API_VERSION(0, 1, 0, 0)

// API_VERSION_1_0: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_API_VERSION_1_0.html
var API_VERSION_1_0 = MAKE_API_VERSION(0, 1, 0, 0)

// API_VERSION_1_1: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_API_VERSION_1_1.html
var API_VERSION_1_1 = MAKE_API_VERSION(0, 1, 1, 0)

// API_VERSION_1_2: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_API_VERSION_1_2.html
var API_VERSION_1_2 = MAKE_API_VERSION(0, 1, 2, 0)

// API_VERSION_MAJOR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_API_VERSION_MAJOR.html
var API_VERSION_MAJOR = apiVersionMajor

// API_VERSION_MINOR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_API_VERSION_MINOR.html
var API_VERSION_MINOR = apiVersionMinor

// API_VERSION_PATCH: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_API_VERSION_PATCH.html
var API_VERSION_PATCH = apiVersionPatch

// API_VERSION_VARIANT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_API_VERSION_VARIANT.html
var API_VERSION_VARIANT = apiVersionVariant

// HEADER_VERSION: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_HEADER_VERSION.html
var HEADER_VERSION = uint32(270)

// HEADER_VERSION_COMPLETE: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_HEADER_VERSION_COMPLETE.html
var HEADER_VERSION_COMPLETE = MAKE_API_VERSION(0, 1, 3, HEADER_VERSION)

// MAKE_API_VERSION: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_MAKE_API_VERSION.html
var MAKE_API_VERSION = makeApiVersion

// MAKE_VERSION: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_MAKE_VERSION.html
var MAKE_VERSION = deprecatedMakeVersion

// VERSION_MAJOR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_VERSION_MAJOR.html
var VERSION_MAJOR = deprecatedVersionMajor

// VERSION_MINOR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_VERSION_MINOR.html
var VERSION_MINOR = deprecatedVersionMinor

// VERSION_PATCH: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_VERSION_PATCH.html
var VERSION_PATCH = deprecatedVersionPatch
