// Code generated by go-vk from vk.xml at 2025-11-20 11:05:56.8178389 -0500 EST m=+2.059250901. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT StructureType = 1000217000
)
