// Code generated by "stringer -output=enum_string_8.go -type=ViewportCoordinateSwizzleNV"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV-0]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV-1]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV-2]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV-3]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV-4]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV-5]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV-6]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV-7]
}

const _ViewportCoordinateSwizzleNV_name = "VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV"

var _ViewportCoordinateSwizzleNV_index = [...]uint16{0, 41, 82, 123, 164, 205, 246, 287, 328}

func (i ViewportCoordinateSwizzleNV) String() string {
	if i < 0 || i >= ViewportCoordinateSwizzleNV(len(_ViewportCoordinateSwizzleNV_index)-1) {
		return "ViewportCoordinateSwizzleNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ViewportCoordinateSwizzleNV_name[_ViewportCoordinateSwizzleNV_index[i]:_ViewportCoordinateSwizzleNV_index[i+1]]
}
