// Code generated by go-vk from vk.xml at 2024-09-12 10:06:37.0369323 -0400 EDT m=+2.028668801. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
