// Code generated by "stringer -output=enum_win32_string_0.go -type=FullScreenExclusiveEXT"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FULL_SCREEN_EXCLUSIVE_DEFAULT_EXT-0]
	_ = x[FULL_SCREEN_EXCLUSIVE_ALLOWED_EXT-1]
	_ = x[FULL_SCREEN_EXCLUSIVE_DISALLOWED_EXT-2]
	_ = x[FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT-3]
}

const _FullScreenExclusiveEXT_name = "FULL_SCREEN_EXCLUSIVE_DEFAULT_EXTFULL_SCREEN_EXCLUSIVE_ALLOWED_EXTFULL_SCREEN_EXCLUSIVE_DISALLOWED_EXTFULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT"

var _FullScreenExclusiveEXT_index = [...]uint8{0, 33, 66, 102, 150}

func (i FullScreenExclusiveEXT) String() string {
	if i < 0 || i >= FullScreenExclusiveEXT(len(_FullScreenExclusiveEXT_index)-1) {
		return "FullScreenExclusiveEXT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FullScreenExclusiveEXT_name[_FullScreenExclusiveEXT_index[i]:_FullScreenExclusiveEXT_index[i+1]]
}
