//go:build darwin

// Code generated by go-vk from vk.xml at 2025-11-20 11:05:56.8407555 -0500 EST m=+2.082167501. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_METAL_SURFACE_EXTENSION_NAME = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION   = 1
)
