//go:build darwin

// Code generated by go-vk from vk.xml at 2024-09-12 10:06:36.854782 -0400 EDT m=+1.846518501. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
