//go:build darwin

// Code generated by go-vk from vk.xml at 2023-12-27 07:44:40.7773785 -0500 EST m=+1.960983101. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
