//go:build darwin

// Code generated by go-vk from vk.xml at 2025-11-13 11:56:02.923021 -0500 EST m=+1.052590876. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_METAL_SURFACE_EXTENSION_NAME = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION   = 1
)
