// Code generated by go-vk from vk.xml at 2025-10-08 11:06:15.734158 -0400 EDT m=+0.554814334. DO NOT EDIT.

package vk

// AccelerationStructureKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureKHR.html
type AccelerationStructureKHR nonDispatchableHandle

// AccelerationStructureNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAccelerationStructureNV.html
type AccelerationStructureNV nonDispatchableHandle

// Buffer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBuffer.html
type Buffer nonDispatchableHandle

// BufferView: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBufferView.html
type BufferView nonDispatchableHandle

// CommandBuffer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandBuffer.html
type CommandBuffer handle

// CommandPool: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCommandPool.html
type CommandPool nonDispatchableHandle

// CuFunctionNVX: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCuFunctionNVX.html
type CuFunctionNVX nonDispatchableHandle

// CuModuleNVX: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkCuModuleNVX.html
type CuModuleNVX nonDispatchableHandle

// DebugReportCallbackEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugReportCallbackEXT.html
type DebugReportCallbackEXT nonDispatchableHandle

// DebugUtilsMessengerEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDebugUtilsMessengerEXT.html
type DebugUtilsMessengerEXT nonDispatchableHandle

// DeferredOperationKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeferredOperationKHR.html
type DeferredOperationKHR nonDispatchableHandle

// DescriptorPool: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorPool.html
type DescriptorPool nonDispatchableHandle

// DescriptorSet: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorSet.html
type DescriptorSet nonDispatchableHandle

// DescriptorSetLayout: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayout.html
type DescriptorSetLayout nonDispatchableHandle

// DescriptorUpdateTemplate: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorUpdateTemplate.html
type DescriptorUpdateTemplate nonDispatchableHandle

// DescriptorUpdateTemplateKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDescriptorUpdateTemplateKHR.html
type DescriptorUpdateTemplateKHR = DescriptorUpdateTemplate

// Device: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDevice.html
type Device handle

// DeviceMemory: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDeviceMemory.html
type DeviceMemory nonDispatchableHandle

// DisplayKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDisplayKHR.html
type DisplayKHR nonDispatchableHandle

// DisplayModeKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDisplayModeKHR.html
type DisplayModeKHR nonDispatchableHandle

// Event: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkEvent.html
type Event nonDispatchableHandle

// Fence: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFence.html
type Fence nonDispatchableHandle

// Framebuffer: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFramebuffer.html
type Framebuffer nonDispatchableHandle

// Image: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImage.html
type Image nonDispatchableHandle

// ImageView: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkImageView.html
type ImageView nonDispatchableHandle

// IndirectCommandsLayoutNV: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkIndirectCommandsLayoutNV.html
type IndirectCommandsLayoutNV nonDispatchableHandle

// Instance: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkInstance.html
type Instance handle

// PerformanceConfigurationINTEL: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPerformanceConfigurationINTEL.html
type PerformanceConfigurationINTEL nonDispatchableHandle

// PhysicalDevice: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPhysicalDevice.html
type PhysicalDevice handle

// Pipeline: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipeline.html
type Pipeline nonDispatchableHandle

// PipelineCache: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineCache.html
type PipelineCache nonDispatchableHandle

// PipelineLayout: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPipelineLayout.html
type PipelineLayout nonDispatchableHandle

// PrivateDataSlotEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPrivateDataSlotEXT.html
type PrivateDataSlotEXT nonDispatchableHandle

// QueryPool: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueryPool.html
type QueryPool nonDispatchableHandle

// Queue: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkQueue.html
type Queue handle

// RenderPass: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkRenderPass.html
type RenderPass nonDispatchableHandle

// Sampler: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSampler.html
type Sampler nonDispatchableHandle

// SamplerYcbcrConversion: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSamplerYcbcrConversion.html
type SamplerYcbcrConversion nonDispatchableHandle

// SamplerYcbcrConversionKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSamplerYcbcrConversionKHR.html
type SamplerYcbcrConversionKHR = SamplerYcbcrConversion

// Semaphore: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSemaphore.html
type Semaphore nonDispatchableHandle

// ShaderModule: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkShaderModule.html
type ShaderModule nonDispatchableHandle

// SurfaceKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSurfaceKHR.html
type SurfaceKHR nonDispatchableHandle

// SwapchainKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSwapchainKHR.html
type SwapchainKHR nonDispatchableHandle

// ValidationCacheEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkValidationCacheEXT.html
type ValidationCacheEXT nonDispatchableHandle

// handle: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_DEFINE_HANDLE.html
type handle uintptr

const (
	NULL_HANDLE handle = 0
)

// nonDispatchableHandle: The Vulkan spec specifically defines a handle as a platform pointer type (i.e., could be 32 bits) and a non-dispatchable handle as a 64 bit type.
// See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_DEFINE_NON_DISPATCHABLE_HANDLE.html
type nonDispatchableHandle uint64
